trigger: none  # Déclenché uniquement par le CI

resources:
  pipelines:
  - pipeline: ci-api
    source: 'Cyna-Api CI'        # Nom exact du pipeline CI dans Azure DevOps
    trigger:
      branches:
        include: [ "main", "dev" ]

pool:
  name: 'CyanPool'

variables:
  - group: 'GHCR'
  - name: FULL_IMAGE
    value: 'ghcr.io/nizardv/cyna-api'
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - name: envName
        value: 'production'
      - name: API_PORT
        value: '4000'
      - name: ASPNETCORE_ENV
        value: 'Production'
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
      - name: envName
        value: 'staging'
      - name: API_PORT
        value: '4001'
      - name: ASPNETCORE_ENV
        value: 'Staging'

stages:
- stage: CD_Cloud
  displayName: 'CD Cloud — Deploy OVH [ $(envName) ]'
  jobs:
  - deployment: Deploy
    environment: ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}PROD${{ else }}DEV${{ end }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            displayName: 'Deploy API sur OVH'
            inputs:
              sshEndpoint: 'OVH-SSH-Connection'
              runOptions: 'inline'
              failOnStdErr: false
              inline: |
                echo "$(GHCR_PAT)" | docker login ghcr.io -u NizardV --password-stdin

                cd ~/cyna-api

                ENV_NAME=$(envName) \
                API_PORT=$(API_PORT) \
                ASPNETCORE_ENVIRONMENT=$(ASPNETCORE_ENV) \
                  docker compose pull api

                ENV_NAME=$(envName) \
                API_PORT=$(API_PORT) \
                ASPNETCORE_ENVIRONMENT=$(ASPNETCORE_ENV) \
                  docker compose up -d --no-build --force-recreate

          - task: SSH@0
            displayName: 'Health check post-deploy'
            inputs:
              sshEndpoint: 'OVH-SSH-Connection'
              runOptions: 'inline'
              failOnStdErr: false
              inline: |
                sleep 5
                curl -f http://localhost:$(API_PORT)/health || exit 1